name: Test Backend
on:
  pull_request:
    paths:
      - ".github/workflows/test-backend.yml"
      - "backend/**"
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Test Backend
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run install:backend:ci
      - name: Test
        env:
          EXTEND_ESLINT: true
        run: npm run test:backend:ci
