name: Test Frontend
on:
  pull_request:
    paths:
      - ".github/workflows/test-frontend.yml"
      - "/front-end/**"
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend
      - name: Install dependencies
      - uses: actions/checkout@v1
        run: npm install
      - name: Build test dependencies
        run: npm run build:dependencies:front-end
      - name: Test
        env:
          EXTEND_ESLINT: true
        run: npm run test:front-end:ci
