name: Test Frontend
on:
  pull_request:
    paths:
      - ".github/workflows/test-frontend.yml"
      - "front-end/**"
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm install:frontend
      - name: Build dependencies
        run: npm build:front-end
      - name: Test
        env:
          CI: false
          EXTEND_ESLINT: true
        run: npm test:front-end:ci
