name: Test Frontend
on:
  pull_request:
    paths:
      - ".github/workflows/test-frontend.yml"
      - "frontend/**"
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run install:frontend:ci
      - name: Build test dependencies
        run: npm run build:frontend
      - name: Test
        env:
          EXTEND_ESLINT: true
        run: npm run test:frontend:ci
